version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/var/www/html
    links:
      - db
    ports:
      - "8000:80"
    environment:
      - TZ=America/Sao_Paulo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - '/app/node_modules'
    ports:
      - "8080:8080"
    links:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - /var/lib/mysql
    command: --max_allowed_packet=2048M
    environment:
      MYSQL_DATABASE: dbase
      MYSQL_USER: dbase
      MYSQL_PASSWORD: dbase
      MYSQL_ROOT_PASSWORD: dbase
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
